<?php

/**
 * @file
 * Contains zarpele_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function zarpele_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the zarpele_migrate module.
    case 'help.page.zarpele_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrating Zarpele Wordpress site to D9.') . '</p>';
      return $output;

    default:
  }
}
